name: Deploy React App to Azure Web App

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    types: [opened, closed, edited]
    branches:
      - 'main'
      - 'feature/*'
  workflow_dispatch:

jobs:
  LintTestJob:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci
      - name: Perform Lint test
        run: npm run lint
      - name: Perform tests
        run: npm run test

  BuildJob:
    needs: LintTestJob
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-dep-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-files
          path: dist/

  DeployJob:
    needs: BuildJob
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-files
          path: dist
      - name: Display Artifact Contents
        run: | 
              pwd
              ls -al
              
      - name: Azure Web App Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NodejsApplication2024'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist/
